name: Execute Cron Job Qiita Advent Calendar 2025 For RSS

on:
  schedule:
    - cron: "40 23 * * *"
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_RSS }}
  FEED_URL: ${{ secrets.FEED_URL}}

jobs:
  run:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.25
    
    - name: Run Go Program
      run: go run main.go -mode=rss -rss=$FEED_URL -limit=10
  